/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define GETTEXT_PACKAGE "raider"

#define LOCALEDIR "/usr/local/share/locale"

#define PACKAGE_VERSION "0.1.0"

