.\"Created with GNOME Manpages Editor Wizard
.\"http://sourceforge.net/projects/gmanedit2

.TH RAIDER 1 "December 6, 2021" "" "Raider"

.SH NAME
raider \- shred your files securely

.SH SYNOPSIS
.B raider
.RI 
.br

.SH DESCRIPTION
The
.B raider 
program is a graphical user interface  for the shredding program called shred, 
included in the GNU Coreutils.
.SH AUTHOR
Alan Beveridge
